# Wazuh - Filebeat configuration file
output:
  elasticsearch:
    hosts: []
    protocol: https
    username: "admin"
    password: "admin"
    ssl:
      certificate_authorities:
        - /etc/filebeat/certs/root-ca.pem
      certificate: "/etc/filebeat/certs/filebeat.pem"
      key: "/etc/filebeat/certs/filebeat-key.pem"
setup:
  template:
    json:
      enabled: true
      path: '/etc/filebeat/wazuh-template.json'
      name: 'wazuh'
  ilm:
    overwrite: true
    enabled: false
filebeat:
  modules:
    - module: wazuh
      alerts:
        enabled: true
      archives:
        enabled: false
