# @formatter:off
apiVersion: v1
kind: Service
metadata:
  labels:
    role: manager
  name: {{ .Release.Name }}-cluster-mgmt-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 1516
    name: cluster-mgmt-svc
  clusterIP: None
  selector:
    role: manager
