# @formatter:off
{{- if .Values.wazuh.manager.enabled }}
{{- if .Values.wazuh.manager.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wazuh.fullname" . }}-manager-ossec-conf
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ossec.conf: {{ toYaml .Values.wazuh.manager.config | b64enc | quote }}
{{- end }}
{{- end }}
