# @formatter:off
{{- if .Values.wazuh.filebeat.enabled }}
{{- if .Values.wazuh.filebeat.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-filebeat-conf
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  filebeat.yml: {{ toYaml .Values.wazuh.filebeat.config | b64enc | quote }}
{{- end }}
{{- end }}
