# @formatter:off
{{- if .Values.wazuh.authd }}
{{- if and .Values.wazuh.authd.agentPassphraseEnabled .Values.wazuh.authd.agentPassphrase }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-authd-passphrase-file
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  authd.pass: {{ .Values.wazuh.authd.agentPassphrase | b64enc | quote }}
{{- end }}
{{- end }}
