# @formatter:off
{{- if .Values.wazuh.worker.enabled }}
{{- if .Values.wazuh.worker.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-worker-ossec-conf
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ossec.conf: {{ toYaml .Values.wazuh.worker.config | b64enc | quote }}
{{- end }}
{{- if .Values.wazuh.worker.filebeat.enabled }}
{{- if .Values.wazuh.worker.filebeat.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-worker-filebeat-conf
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  filebeat.yml: {{ toYaml .Values.wazuh.worker.filebeat.config | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
